import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
from api import demo_web_app
from api import GPT, Example, UIConfig


gpt = GPT(engine="davinci",temperature=0.5,max_tokens=100)

gpt.add_example(Example("A story about the boy who cried wolf","Once upon a time, there lived a shepherd boy who was bored watching his flock of sheep on the hill. To amuse himself, he shouted, “Wolf! Wolf! The sheep are being chased by the wolf!” The villagers came running to help the boy and save the sheep. They found nothing and the boy just laughed looking at their angry faces. “Don’t cry ‘wolf’ when there’s no wolf boy!”, they said angrily and left. The boy just laughed at them. After a while, he got bored and cried ‘wolf!’ again, fooling the villagers a second time. The angry villagers warned the boy a second time and left. The boy continued watching the flock. After a while, he saw a real wolf and cried loudly, “Wolf! Please help! The wolf is chasing the sheep. Help!” But this time, no one turned up to help. By evening, when the boy didn’t return home, the villagers wondered what happened to him and went up the hill. The boy sat on the hill weeping. “Why didn’t you come when I called out that there was a wolf?” he asked angrily. “The flock is scattered now”, he said. An old villager approached him and said, “People won’t believe liars even when they tell the truth. We’ll look for your sheep tomorrow morning. Let’s go home now”."))
gpt.add_example(Example("The Midas Touch","In ancient Greek, there was a king named Midas. He had a lot of gold and everything he needed. He also had a beautiful daughter. Midas loved his gold very much, but he loved his daughter more than his riches. One day, a satyr named Silenus got drunk and passed out in Midas’ rose garden. Believing that Satyrs always bring good luck, Midas lets Silenus rest in his palace until he is sober, against the wishes of his wife and daughter. Silenus is a friend of Dionysus, the god of wine and celebration. Upon learning Midas’ kindness towards his friend, Dionysus decides to reward the keg. When asked to wish for something, Midas says “I wish everything I touch turns to gold”. Although Dionysus knew it was not a great idea, he granted Midas his wish. Happy that his wish was granted, Midas went around touching random things in the garden and his palace and turned them all into gold. He touched an apple, and it turned into a shiny gold apple. His subjects were astonished but happy to see so much gold in the palace. In his happiness, Midas went and hugged his daughter, and before he realized, he turned her into a lifeless, golden statue! Aghast, Midas ran back to the garden and called for Dionysus. He begged the god to take away his power and save his daughter. Dionysus gives Midas a solution to change everything back to how it was before the wish. Midas learned his lesson and lived the rest of his life contended with what he had. "))
gpt.add_example(Example("The Golden Egg","Once upon a time, a farmer had a goose that laid a golden egg every day. The egg provided enough money for the farmer and his wife for their day-to-day needs. The farmer and his wife were happy for a long time. But one day, the farmer got an idea and thought, “Why should I take just one egg a day? Why can’t I take all of them at once and make a lot of money?” The foolish farmer’s wife also agreed and decided to cut the goose’s stomach for the eggs. As soon as they killed the bird and opened the goose’s stomach, to find nothing but guts and blood. The farmer, realizing his foolish mistake, cries over the lost resource! The English idiom “kill not the goose that lays the golden egg” was also derived from this classic story. "))
gpt.add_example(Example("The Miser And His Gold","An old miser lived in a house with a garden. The miser hid his gold coins in a pit under some stones in the garden. Every day, before going to bed, the miser went to the stones where he hid the gold and counted the coins. He continued this routine every day, but not once did he spend the gold he saved. One day, a thief who knew the old miser’s routine, waited for the old man to go back into his house. After it was dark, the thief went to the hiding place and took the gold. The next day, the old miser found that his treasure was missing and started crying loudly. His neighbor heard the miser’s cries and inquired about what happened. On learning what happened, the neighbor asked, “Why didn’t you save the money inside the house? It would’ve been easier to access the money when you had to buy something!” “Buy?”, said the miser. “I never used the gold to buy anything. I was never going to spend it.” On hearing this, the neighbor threw a stone into the pit and said, “If that is the case, save the stone. It is as worthless as the gold you have lost”."))
gpt.add_example(Example("The Tortoise And The Bird","A tortoise was resting under a tree, on which a bird had built its nest. The tortoise spoke to the bird mockingly, “What a shabby home you have! It is made of broken twigs, it has no roof, and looks crude. What’s worse is that you had to build it yourself. I think my house, which is my shell, is much better than your pathetic nest”. “Yes, it is made of broken sticks, looks shabby and is open to the elements of nature. It is crude, but I built it, and I like it.” “I guess it’s just like any other nest, but not better than mine”, said the tortoise. “You must be jealous of my shell, though.” “On the contrary”, the bird replied. “My home has space for my family and friends; your shell cannot accommodate anyone other than you. Maybe you have a better house. But I have a better home”, said the bird happily."))

config = UIConfig(description="Enter a story title to generate story",button_text="Generate Story",placeholder="A story about the boy who cried wolf")

demo_web_app(gpt, config)